version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    security-updates: true

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
